# ░░░░░░░░░░░░░░░   BarrierPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/barrierblus.70510/
#  Wiki: https://github.com/momoservertw/BarrierPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 7
Debugging: false
Check-Updates: true

# Display near creative blocks like barriers.
# Permission: barrierplus.see.GROUP or barrierplus.see.*
# More information: https://github.com/momoservertw/BarrierPlus/wiki/See
See:
  Enable: false
  Settings:
    Distance: 10
    Cooldown:
      Interval: 60
      Message: false
  Groups:
    Barrier:
      Enable: false
      Creative: false
      Particle: "Barrier"
      Types:
        - BARRIER
      Conditions:
        - "%player_gamemode%!=CREATIVE"
    Structure_void:
      Enable: false
      Particle: "Crit_Magic"
      Types:
        - STRUCTURE_VOID
    Example:
      Enable: false
      Creative: true
      Particle: ""
      Types: []
      Location: []
      Conditions: []

# These creative blocks will need permission to place.
# Permission: barrierplus.place.MATERIAL or barrierplus.place.*
# More information: https://github.com/momoservertw/BarrierPlus/wiki/Place
Place:
  Enable: false
  Groups:
    Creative:
      Enable: false
      Types:
        - BARRIER
        - STRUCTURE_VOID
        - BEDROCK
    Example:
      Enable: false
      Types: []
      Location: []
      Conditions: []

# Control blocks destroy conditions. The creative blocks can be broken by the menu.
# Permission: barrierplus.destroy.MATERIAL or barrierplus.destroy.*
# More information: https://github.com/momoservertw/BarrierPlus/wiki/Destroy
Destroy:
  Enable: false
  Settings:
    Help-Message: true
    Menu-Break:
      Cooldown:
        Interval: 20
        Message: false
    Default:
      Menu:
        Break: true
        Drop: true
      Vanilla:
        Break: false
        Drop: false
      Explode:
        Break: false
        Drop: false
  Groups:
    Creative:
      Enable: false
      Types:
        - BARRIER
        - STRUCTURE_VOID
    Bedrock:
      Enable: false
      Types:
        - BEDROCK
      Location:
        - "Bedrock_World"
        - "Bedrock_Nether"
    Example:
      Enable: false
      Types: []
      Menu:
        Break: true
        Drop: true
      Vanilla:
        Break: false
        Drop: false
      Explode:
        Break: false
        Drop: false
      Location: []
      Conditions: []