name: BarrierPlus
main: tw.momocraft.barrierplus.BarrierPlus
author: Momocraft
api-version: 1.14
version: 1.0.4
description: Adding creative blocks in your server.
softdepend: [Vault, Residence]

commands:
  barrierplus:
    description: Displays main command menu.
    permission: barrierplus.use
    usage: |
      /barrierplus

permissions:
  barrierplus.*:
    description: Allows use of all commands and feature.
    default: op
    children:
      barrierplus.all: true
  barrierplus.all:
    description: Allows use of all commands and feature.
    default: op
    children:
      barrierplus.use: true
      barrierplus.see.*: true
      barrierplus.place.*: true
      barrierplus.destroy.*: true
  barrierplus.use:
    description: Allows use of basic commands.
    default: true
  barrierplus.see.*:
    description: Allows to see near blocks.
    default: op
    children:
      barrierplus.see.barrier: true
  barrierplus.see.barrier:
    description: Allows to see barriers.
    default: op
  barrierplus.place.*:
    description: Allows place all blocks in config.
    default: op
    children:
      barrierplus.place.barrier: true
      barrierplus.place.bedrock: true
  barrierplus.place.barrier:
    description: Allows to place barriers.
    default: op
  barrierplus.place.bedrock:
    description: Allows to place bedrocks.
    default: op
  barrierplus.detroy.*:
    description: Allows destroy all blocks in config by server menu item.
    default: op
    children:
      barrierplus.destroy.barrier: true
      barrierplus.destroy.bedrock: true
  barrierplus.destroy.barrier:
    description: Allows to destroy barriers.
    default: op
  barrierplus.destroy.bedrock:
    description: Allows to destroy bedrocks.
    default: op