# --{ =-=-=-=-=-=-=-=-=-= BarrierPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
Config-Version: 6
Check-Updates: true
Debugging: false

General:
  Settings:
    Features:
      # Changed these options need to restart the server.
      Hook:
        Vault: true
        PlaceHolderAPI: true
        Residence: true
        PlayerPoints: true
        ItemJoin: true
  # The menu item for some events like showing blocks or destroying it.
  # If you don't have a menu in your server, you can set Item Name to "" to use a vanilla item.
  # Support: ItemJoin
  Menu:
    ItemJoin: ""
    Item:
      Type: "PLAYER_HEAD"
      Name: "&e&lMy &6&lMenu"
  Location:
    NormalWorlds:
      Worlds:
        - world
    NetherWorlds:
      Worlds:
        - world_nether
    EndWorlds:
      Worlds:
        - world_the_end
    NormalBorder:
      Worlds:
        - world
      Area:
        S: 10000
    Bedrock_World:
      Worlds:
        - world
      Area:
        Y: ">= 5"
    Bedrock_Nether:
      Worlds:
        - world_nether
      Area:
        Y: "5 ~ 123"

# Blocks shop.
# Permission: barrierplus.command.buy
# Item permission: barrierplus.buy.MATERIAL or barrierplus.buy.*
# More information: https://github.com/momoservertw/BarrierPlus/wiki/Buy
Buy:
  Enable: false
  Groups:
    Creative:
      Enable: true
      # Price-Type: "money" or "points". "points" only support PlayerPoints.
      Price-Type: points
      Price: 25
      Amount: 64
      Types:
        - BARRIER
        - STRUCTURE_VOID
        - BEDROCK

# Display near creative blocks like barriers.
# Permission: barrierplus.see.GROUP or barrierplus.see.*
# More information: https://github.com/momoservertw/BarrierPlus/wiki/See
See:
  Enable: false
  Settings:
    Distance: 10
    Cooldown:
      Interval: 60
      Message: false
  Groups:
    Barrier:
      Enable: true
      Creative: false
      Particle:
        Type: BARRIER
        Amount: 1
        Times: 1
        Interval: 10
      Types:
        - BARRIER
    Structure_void:
      Enable: true
      Particle:
        Type: CRIT_MAGIC
        Amount: 2
        Times: 10
        Interval-Tick: 10
      Types:
        - STRUCTURE_VOID

# These creative blocks will need permission to place.
# Permission: barrierplus.place.MATERIAL or barrierplus.place.*
# More information: https://github.com/momoservertw/BarrierPlus/wiki/Place
Place:
  Enable: false
  Groups:
    Creative:
      Enable: true
      Types:
        - BARRIER
        - STRUCTURE_VOID
    Bedrock:
      Enable: true
      Types:
        - BEDROCK
      Prevent:
        Location:
          - Bedrock_World
          - Bedrock_Nether

# Control blocks destroy conditions. The creative blocks can be broken by the menu.
# Permission: barrierplus.destroy.MATERIAL or barrierplus.destroy.*
# More information: https://github.com/momoservertw/BarrierPlus/wiki/Destroy
Destroy:
  Enable: false
  Settings:
    Help-Message: true
    Menu-Break:
      Cooldown:
        Interval: 60
        Message: false
    Default:
      Menu:
        Break: true
        Drop: true
      Vanilla:
        Break: false
        Drop: false
      Explode:
        Break: false
        Drop: false
  Groups:
    Barrier:
      Enable: true
      Types:
        - BARRIER
        - STRUCTURE_VOID
    Bedrock:
      Enable: true
      Types:
        - BEDROCK
      Prevent:
        Location:
          - Bedrock_World
          - Bedrock_Nether

Message:
  prefix: '&7[&dBarrierPlus&7]&r '
  noPermission: '&cYou do not have permission to use that command!'
  unknownCommand: '&cUnknown command, See &e/barrierplus help &cfor a list of commands.'
  configReload: '&fConfiguration(s) Reloaded!'
  cooldown: '&fPlease try it again later.'
  targetNotFound: '&cThe player &c%targetplayer% &ccould not be found!'
  BarrierPlus:
    Commands:
      title: "&8▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩ &d&lBarrierPlus &8▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩"
      help: "&a/barrierplus help &8- &7This help menu."
      reload: "&a/barrierplus reload &8- &7Reloads config file."
      buy: "&a/barrierplus buy <item> &8- &7Buy creative items."
      buyOther: "&a/barrierplus buy <item> [player] &8- &7Execute buy creative items command to a player."
    noPermDestroy: '&cYou dont have &6build &cpermission<s> here.'
    noPermPlace: '&cYou dont have permission to place this block.'
    noPermBreak: '&cYou dont have permission to break this block.'
    placeLocFail: '&7You cannot place the %item% in this position.'
    breakHelp: '&7Holding menu and "&eleft-click + shift&7" to break this block.'
    breakLocFail: '&7You cannot break the %item% in this position.'
    noShopItem: '&cYou can not buy this block.'
    inventoryFull: '&cYou dont have enough inventory space.'
    targetInventoryFull: '&c%targetplayer% dont have enough inventory space.'
    buyDisable: '&cThis feature is disabled.'
    buyNoPerm: '&cYou do not have permission to buy %item%.'
    buySuccess: '&aSuccess buy &e%item% x%amount% &afor %price% %pricetype% &8- &a%pricetype%: %balance%'
    buyTargetSuccess: '&aSuccess buy &e%item% x%amount% &afor %price% %pricetype% for %targetplayer% &8- &a%pricetype%: %balance%'
    buyNotEnoughMoney: '&cYou need &e%price% %pricetype%&c to buy %item% x%amount% &8- &c%pricetype%: %balance%.'
    buyTargetNotEnoughMoney: '&c%targetplayer% need &e%price% %pricetype%&c to buy %item% x%amount% &8- &c%pricetype%: %balance%'
    Translate:
      money: 'money'
      points: 'points'
      BARRIER: 'barrier'
      STRUCTURE_VOID: 'structure_void'
      BEDROCK: 'bedrock'