# --{ =-=-=-=-=-=-=-=-=-= BarrierPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
Config-Version: 4
Log-Coloration: true
Debugging: false

# The menu item for some events like showing barriers or destroying it.
# Item types: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# If you don't have a menu in your server, you can set Item-Name to '' to use a vanilla item.
Menu:
  Item-Type: 'PLAYER_HEAD'
  Item-Name: '&e&lMy &6&lMenu'

# Price-Type can set to "money" or "points". PlayerPointsAPI only support PlayerPoints.
# PlayerPoints: https://dev.bukkit.org/projects/playerpoints
# If you don't set option "Amount", it will give player the max stack size of that item like barrier x64.
# Amount can set overy than the max stack size.

# Buy command: /barrierplus buy <item> [player]
# Command permission: barrierplus.command.buy
# Command permission for other player: barrierplus.command.buy.other
# Item permission: barrierplus.buy.MATERIAL or barrierplus.buy.*

# If you want to give the items to player for free, you can use give command.
# Give command: /barrierplus give <item> [amount] [player]
# Command permission: barrierplus.command.give
# Command permission for other player: barrierplus.command.give.other
# Item [ermission: barrierplus.give.MATERIAL or barrierplus.give.*
Buy:
  List:
    BARRIER:
      Price-Type: points
      Price: 25
      Amount: 64
    STRUCTURE_VOID:
      Price-Type: points
      Price: 25
    BEDROCK:
      Price-Type: points
      Price: 25
    DIRT:
      Price-Type: money
      Price: 1000
      Amount: 640

# You can add any type of blocks and custom display particle.
# Particle type: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
# Permission: barrierplus.see.MATERIAL or barrierplus.see.*
See:
  Enable: false
  Distance: 10
  # You can set cooldown to 0 (tick) to disable this feature.
  Cooldown: 60
  Cooldown-Message: false
  List:
    BARRIER:
      Creative-Mode: false
      Particle: BARRIER
      Amount: 1
      Times: 1
      Interval-Tick: 10
    STRUCTURE_VOID:
      Particle: CRIT_MAGIC
      Amount: 2
      Times: 10
      Interval-Tick: 10

# These blocks will need permission to place.
# Permission: barrierplus.place.MATERIAL or barrierplus.place.*
Place:
  Enable: false
  List:
    - BARRIER
    - STRUCTURE_VOID
    - BEDROCK

# These blocks can destroy by menu.
# Permission: barrierplus.destroy.MATERIAL or barrierplus.destroy.*
Destroy:
  Enable: false
  # Send a help message to player if they try to break the block which disable vanilla break.
  Menu-Break:
    Help-Message: true
    # Menu-break cooldown.You can set 0 (tick) to disable this feature.
    Cooldown: 10
    Cooldown-Message: true
  # It will cancel vanilla break event and only allows player to use menu to break blocks.
  # Default settings:
  #   Menu-Break: true
  #   Menu-Drop: true
  #   Vanilla-Break: false
  #   Vanilla-Drop: false
  #   Explode-Break: false
  #   Explode-Drop: false
  List:
    BARRIER:
      Menu-Break: true
      Menu-Drop: true
      Vanilla-Break: false
      Vanilla-Drop: false
      Explode-Break: false
      Explode-Drop: false
    STRUCTURE_VOID: []
    BEDROCK: []

Message:
  prefix: '&7[&dBarrierPlus&7]&r '
  noPermission: '&cYou do not have permission to use that command!'
  unknownCommand: '&cUnknown command, See &e/barrierplus help &cfor a list of commands.'
  configReload: '&fConfiguration(s) Reloaded!'
  cooldown: '&fPlease try it again later.'
  targetNotFound: '&cThe player &c%targetplayer% &ccould not be found!'
  BarrierPlus:
    noPermDestroy: '&cYou dont have &6build &cpermission<s> here.'
    noPermPlace: '&cYou dont have permission to place that block.'
    breakHelp: '&7Holding menu and "&eleft-click + shift&7" to break this block.'
    noShopItem: '&cYou can not buy this block.'
    inventoryFull: '&cYou dont have enough inventory space.'
    targetInventoryFull: '&c%targetplayer% dont have enough inventory space.'
    buySuccess: '&aSuccess buy &e%item% x%amount% &afor %price% %pricetype% &8- &a%pricetype%: %balance%.'
    buyTargetSuccess: '&aSuccess buy &e%item% x%amount% &afor %price% %pricetype% for %targetplayer% &8- &a%pricetype%: %balance%.'
    buyNotEnoughMoney: '&cYou need &e%price% %pricetype%&c to buy %item% x%amount% &8- &c%pricetype%: %balance%.'
    buyTargetNotEnoughMoney: '&c%targetplayer% need &e%price% %pricetype%&c to buy %item% &%amount% &8- &c%pricetype%: %balance%.'
    giveSuccess: '&aSuccess give &e%item% &7x%amount%.'
    giveTargetSuccess: '&aSuccess give &e%item% &7x%amount% &afor %targetplayer%.'