# --{ =-=-=-=-=-=-=-=-=-= BarrierPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
config-Version: 3
Metrics-Logging: true
Log-Coloration: true

# The menu item for some events like showing barriers or destroying it.
# Item type can find here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# If you don't have a menu in your server, you can set Item-Name to '' to use a vanilla item.
Menu:
  Item-Type: 'PLAYER_HEAD'
  Item-Name: '&e&lMy &6&lMenu'

# You can add any type of blocks and custom display particle.
# Particle type can find here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
# Permission: barrierplus.see.MATERIAL or barrierplus.see.*
See:
  Enable: true
  Distance: 10
  Cooldown: 3
  Cooldown-Message: false
  Block-List:
    BARRIER:
      Particle: BARRIER
      Amount: 1
      # The times particle will display.
      Times: 1
      # The interval between particle show again.
      Interval-Tick: 10
    STRUCTURE_VOID:
      Creative-Mode: true
      Particle: CRIT_MAGIC
      Amount: 2
      Times: 10
      Interval-Tick: 10

# These blocks will need permission to place.
# Permission: barrierplus.place.MATERIAL or barrierplus.place.*
Place:
  Enable: true
  Block-List:
    - BARRIER
    - STRUCTURE_VOID
    - BEDROCK

# These blocks can destroy by menu.
# You can cancel vanilla break event and only allows player to use menu to break blocks.
# Permission: barrierplus.destroy.MATERIAL or barrierplus.destroy.*
Destroy:
  Enable: true
  # Send a help message to player if they try to break the block which disable vanilla break.
  Break-Help-Message: true
  Block-List:
    BARRIER:
      Vanilla-Break: false
    STRUCTURE_VOID:
      Vanilla-Break: false
    BEDROCK:
      Vanilla-Break: false

Message:
  Prefix: '&7[&dBarrierPlus&7]&r '
  No-Perm-Destroy: '&cYou dont have &6build &cpermission<s> here.'
  No-Perm-Place: '&cYou dont have permission to place that block.'
  Break-Help: '&fHolding menu and "left-click + shift" to break this block.'
  Cooldown: '&fPlease try it again later.'
  Commands:
    noPermission: '&cYou do not have permission to use that command!'