name: BarrierPlus
main: tw.momocraft.barrierplus.BarrierPlus
author: Momocraft
api-version: 1.13
version: 1.1.1
description: Control blocks place and destroy conditions, and display nearly invisible blocks like barriers.
softdepend: [Vault, Residence, PlayerPoints, PlaceHolderAPI]

commands:
  barrierplus:
    description: Displays main command menu.
    permission: barrierplus.use
    usage: |
      /barrierplus
  barrierplus reload:
    description: Reloads all configuration files and caches any new data.
    permission: barrierplus.command.version
    usage: |
      /barrierplus reload
  barrierplus version:
    description: Check the plugin version.
    permission: barrierplus.command.version
    usage: |
      /barrierplus version
  barrierplus buy:
    description: To buy creative blocks.
    permission: barrierplus.command.buy
    usage: |
      /barrierplus buy
  barrierplus buy barrier:
    description: To buy barriers.
    permission: barrierplus.command.buy
    usage: |
      /barrierplus buy barrier
  barrierplus buy structure_void:
    description: To buy structure_voids.
    permission: barrierplus.command.buy
    usage: |
      /barrierplus buy structure_void
  barrierplus buy bedrock:
    description: To buy bedrocks.
    permission: barrierplus.command.buy
    usage: |
      /barrierplus buy bedrock
  barrierplus give:
    description: To give creative blocks.
    permission: barrierplus.command.give
    usage: |
      /barrierplus give
  barrierplus give barrier:
    description: To give barriers.
    permission: barrierplus.command.give
    usage: |
      /barrierplus give barrier
  barrierplus give structure_void:
    description: To give structure_voids.
    permission: barrierplus.command.give
    usage: |
      /barrierplus give structure_void
  barrierplus give bedrock:
    description: To give bedrocks.
    permission: barrierplus.command.give
    usage: |
      /barrierplus give bedrock

permissions:
  barrierplus.*:
    description: Allows use of all commands and feature.
    default: op
    children:
      barrierplus.use: true
      barrierplus.command.*: true
      barrierplus.see.*: true
      barrierplus.place.*: true
      barrierplus.destroy.*: true
      barrierplus.buy.*: true
      barrierplus.give.*: true
      barrierplus.bypass.*: true
  barrierplus.use:
    description: Allows use of basic commands.
    default: true
  barrierplus.command.*:
    description: Allows use all commands.
    default: op
    children:
      barrierplus.command.reload: true
      barrierplus.command.version: true
      barrierplus.command.buy: true
      barrierplus.command.buy.other: true
      barrierplus.command.give: true
      barrierplus.command.give.other: true
  barrierplus.command.reload:
    description: Allows use of command /barrierplus reload.
    default: op
  barrierplus.command.version:
    description: Allows use of command /barrierplus version.
    default: op
  barrierplus.command.buy:
    description: Allows to use command /barrierplus buy.
    default: op
  barrierplus.command.buy.other:
    description: Allows to use command /barrierplus buy for other player.
    default: op
  barrierplus.command.give:
    description: Allows to use command /barrierplus give.
    default: op
  barrierplus.command.give.other:
    description: Allows to use command /barrierplus give for other player.
    default: op
  barrierplus.see.*:
    description: Allows to see near blocks.
    default: op
    children:
      barrierplus.see.barrier: true
      barrierplus.see.structure_void: true
  barrierplus.see.barrier:
    description: Allows to see barriers.
    default: op
  barrierplus.see.structure_void:
    description: Allows to see structure_void.
    default: op
  barrierplus.place.*:
    description: Allows place all blocks in config.
    default: op
    children:
      barrierplus.place.barrier: true
      barrierplus.place.structure_void: true
      barrierplus.place.bedrock: true
  barrierplus.place.barrier:
    description: Allows to place barriers.
    default: op
  barrierplus.place.structure_void:
    description: Allows to place structure_void.
    default: op
  barrierplus.place.bedrock:
    description: Allows to place bedrocks.
    default: op
  barrierplus.destroy.*:
    description: Allows destroy all blocks in config by server menu item.
    default: op
    children:
      barrierplus.destroy.barrier: true
      barrierplus.destroy.structure_void: true
      barrierplus.destroy.bedrock: true
  barrierplus.destroy.barrier:
    description: Allows to destroy barriers.
    default: op
  barrierplus.destroy.structure_void:
    description: Allows to destroy structure_void.
    default: op
  barrierplus.destroy.bedrock:
    description: Allows to destroy bedrocks.
    default: op
  barrierplus.buy.*:
    description: Allows to buy all blocks.
    default: op
    children:
      barrierplus.buy.barrier: true
      barrierplus.buy.structure_void: true
      barrierplus.buy.bedrock: true
  barrierplus.buy.barrier:
    description: Allows to buy barriers.
    default: op
  barrierplus.buy.structure_void:
    description: Allows to buy structure_voids.
    default: op
  barrierplus.buy.bedrock:
    description: Allows to buy bedrocks.
    default: op
  barrierplus.give.*:
    description: Allows to give all blocks.
    default: op
    children:
      barrierplus.give.barrier: true
      barrierplus.give.structure_void: true
      barrierplus.give.bedrock: true
  barrierplus.give.barrier:
    description: Allows to give barriers.
    default: op
  barrierplus.give.structure_void:
    description: Allows to give structure_voids.
    default: op
  barrierplus.give.bedrock:
    description: Allows to give bedrocks.
    default: op
  barrierplus.bypass.*:
    description: Bypass all event's permission and limits.
    default: op